Repository 42-cub3d/cub3d, pull requests merged in 2022-07, with the labels that each got.

#6 Makefile merge
  .gitignore
  Makefile
  cub3D
  cub3d.h
  libmlx.dylib
  minilibx_mms_20200219/Makefile
  minilibx_mms_20200219/font.c
  minilibx_mms_20200219/interface.o
  minilibx_mms_20200219/interface.swift
  minilibx_mms_20200219/libmlx.dylib
  minilibx_mms_20200219/man/man3/mlx.3
  minilibx_mms_20200219/man/man3/mlx_loop.3
  minilibx_mms_20200219/man/man3/mlx_new_image.3
  minilibx_mms_20200219/man/man3/mlx_new_window.3
  minilibx_mms_20200219/man/man3/mlx_pixel_put.3
  minilibx_mms_20200219/mlx.h
  minilibx_mms_20200219/mlx_image.o
  minilibx_mms_20200219/mlx_image.swift
  minilibx_mms_20200219/mlx_image.swiftdoc
  minilibx_mms_20200219/mlx_image.swiftmodule
  minilibx_mms_20200219/mlx_image.swiftsourceinfo
  minilibx_mms_20200219/mlx_init.o
  minilibx_mms_20200219/mlx_init.swift
  minilibx_mms_20200219/mlx_init.swiftdoc
  minilibx_mms_20200219/mlx_init.swiftmodule
  minilibx_mms_20200219/mlx_init.swiftsourceinfo
  minilibx_mms_20200219/mlx_png.c
  minilibx_mms_20200219/mlx_png.o
  minilibx_mms_20200219/mlx_rgb.c
  minilibx_mms_20200219/mlx_string_put.c
  minilibx_mms_20200219/mlx_string_put.o
  minilibx_mms_20200219/mlx_window.o
  minilibx_mms_20200219/mlx_window.swift
  minilibx_mms_20200219/mlx_window.swiftdoc
  minilibx_mms_20200219/mlx_window.swiftmodule
  minilibx_mms_20200219/mlx_window.swiftsourceinfo
  minilibx_mms_20200219/mlx_xpm.c
  minilibx_mms_20200219/mlx_xpm.o
  srcs/main.c
  srcs/main.o
Labels: work

#13 delete useless file
  library/libft/main.c
  minilibx_mms_20210621/Makefile
  minilibx_mms_20210621/font.c
  minilibx_mms_20210621/interface.o
  minilibx_mms_20210621/interface.swift
  minilibx_mms_20210621/libmlx.dylib
  minilibx_mms_20210621/man/man3/mlx.3
  minilibx_mms_20210621/man/man3/mlx_loop.3
  minilibx_mms_20210621/man/man3/mlx_new_image.3
  minilibx_mms_20210621/man/man3/mlx_new_window.3
  minilibx_mms_20210621/man/man3/mlx_pixel_put.3
  minilibx_mms_20210621/mlx.h
  minilibx_mms_20210621/mlx_image.o
  minilibx_mms_20210621/mlx_image.swift
  minilibx_mms_20210621/mlx_image.swiftdoc
  minilibx_mms_20210621/mlx_image.swiftmodule
  minilibx_mms_20210621/mlx_image.swiftsourceinfo
  minilibx_mms_20210621/mlx_init.o
  minilibx_mms_20210621/mlx_init.swift
  minilibx_mms_20210621/mlx_init.swiftdoc
  minilibx_mms_20210621/mlx_init.swiftmodule
  minilibx_mms_20210621/mlx_init.swiftsourceinfo
  minilibx_mms_20210621/mlx_png.c
  minilibx_mms_20210621/mlx_png.o
  minilibx_mms_20210621/mlx_rgb.c
  minilibx_mms_20210621/mlx_string_put.c
  minilibx_mms_20210621/mlx_string_put.o
  minilibx_mms_20210621/mlx_window.o
  minilibx_mms_20210621/mlx_window.swift
  minilibx_mms_20210621/mlx_window.swiftdoc
  minilibx_mms_20210621/mlx_window.swiftmodule
  minilibx_mms_20210621/mlx_window.swiftsourceinfo
  minilibx_mms_20210621/mlx_xpm.c
  minilibx_mms_20210621/mlx_xpm.o
  srcs/get_map.c
  srcs/main.c
Labels: bug, refactor

#19 add parse_map and check error
  .gitignore
  Makefile
  include/get_map.h
  libmlx.dylib
  library/.gitignore
  library/Makefile
  maps/error_map1.cub
  maps/error_map2.cub
  maps/only_map1.cub
  srcs/check_map_error.c
  srcs/get_map.c
Labels: Priority: ⭑⭑⭑, Status: ✅

#22 texture parsing & code merge
  .gitignore
  Makefile
  include/cub3d.h
  include/get_map.h
  library/Makefile
  library/libft/ft_libc_stdlib.c
  library/libft/ft_split_delimiter.c
  library/libft/libft.h
  map/err1.cub
  map/err2.cub
  map/err3.cub
  map/err4.cub
  map/infile0.cub
  map/infile1.cub
  map/infile2.cub
  map/infile3.cub
  map/infile4.cub
  srcs/get_color.c
  srcs/get_texture.c
  srcs/main.c
  srcs/parse_map.c
Labels: Priority: ⭑⭑⭑, Status: ✅, Bug: 🐞, Work: ⌨

#24 Wchae
  Makefile
  cub3D
  include/cub3d.h
  include/get_map.h
  maps/error_corner_1.cub
  maps/error_corner_2.cub
  maps/error_corner_3.cub
  maps/error_corner_4.cub
  srcs/get_color.c
  srcs/main.c
  srcs/map_get_map.c
  srcs/map_get_map_error.c
  srcs/parse_map.c
Labels: Priority: ⭑⭑⭑, Status: ✅, Work: ⌨

#26 file name change & compile fix
  Makefile
  cub3D
  include/cub3d.h
  include/get_map.h
  library/libft/libft.h
  srcs/main.c
  srcs/parse_get_color.c
  srcs/parse_get_map.c
  srcs/parse_get_map_error.c
  srcs/parse_get_texture.c
  srcs/parse_init.c
Labels: Priority: ⭑⭑⭑, Status: ✅, Work: ⌨

#27 add feature print_map
  include/get_map.h
  srcs/parse_get_map.c
Labels: Priority: ⭑⭑, Work: ⌨

#28 parse done and add some feature and add basic mlx part
  Makefile
  cub3D
  include/cub3d.h
  include/get_map.h
  include/key_event.h
  map/infile4.cub
  srcs/main.c
  srcs/mlx_init.c
  srcs/mlx_key_event.c
  srcs/parse_get_color.c
  srcs/parse_get_map.c
  srcs/parse_get_map_error.c
  srcs/parse_get_texture.c
  srcs/parse_init.c
Labels: Priority: ⭑⭑⭑, Status: ✅, Work: ⌨

#29 refactoring parse_part
  cub3D
  include/cub3d.h
  srcs/main.c
  srcs/mlx_key_event.c
  srcs/parse_get_color.c
  srcs/parse_get_map.c
  srcs/parse_init.c
Labels: Refactor: 🛠

#30 edit... leaks case
  Makefile
  cub3D
  include/get_map.h
  map/infile4.cub
  srcs/main.c
  srcs/mlx_tools.c
  srcs/parse_get_map.c
  srcs/parse_get_texture.c
Labels: Bug: 🐞

#32 [fix] map error check _ side case
  Makefile
  cub3D
  include/cub3d.h
  include/ray_casting.h
  libmlx.dylib
  map/infile5.cub
  srcs/main.c
  srcs/parse_get_map.c
  srcs/parse_get_map_error.c
  srcs/parse_init.c
Labels: Status: ✅, Bug: 🐞

#33 [work] rotate view done
  Makefile
  cub3D
  include/cub3d.h
  include/ray_casting.h
  srcs/main.c
  srcs/mlx_key_event.c
  srcs/mlx_tools.c
  srcs/ray_init.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, Work: ⌨

#37 [add] w s key
  cub3D
  include/cub3d.h
  srcs/mlx_key_event.c
Labels: Priority: ⭑⭑⭑, Status: ✅, Work: ⌨

#39 [fix] floor, ceiling color, close fd
  cub3D
  include/cub3d.h
  leak_test.sh
  map/infile5.cub
  srcs/main.c
  srcs/mlx_key_event.c
  srcs/mlx_tools.c
  srcs/parse_init.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Refactor: 🛠

#41 [fix] segv, stuck field
  Libft.mk
  Makefile
  cub3D
  include/cub3d.h
  include/get_map.h
  include/ray_casting.h
  libmlx.dylib
  library/libft/Makefile
  map/infile4e.cub
  map/infile4n.cub
  map/infile4s.cub
  map/infile4w.cub
  srcs/main.c
  srcs/mlx_key_event.c
  srcs/mlx_tools.c
  srcs/parse_get_map.c
  srcs/parse_get_map_error.c
  srcs/parse_get_texture.c
  srcs/ray_init.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Bug: 🐞

#42 [fix] player view start point - clear
  Makefile
  cub3D
  include/cub3d.h
  srcs/main.c
  srcs/mlx_key_event.c
  srcs/mlx_key_move.c
  srcs/mlx_key_rotate_view.c
  srcs/mlx_tools.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Bug: 🐞

#44 [done] a d player move key
  cub3D
  include/cub3d.h
  srcs/main.c
  srcs/mlx_key_move.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Todo: ⌨

#45 [done] texture mapping
  Makefile
  cub3D
  img/diamond_block.xpm
  img/gold_block.xpm
  img/grass_block.xpm
  img/stone_bricks.xpm
  include/cub3d.h
  include/get_map.h
  include/ray_casting.h
  map/err4.cub
  map/infile4e.cub
  srcs/main.c
  srcs/mlx_key_event.c
  srcs/mlx_key_move.c
  srcs/mlx_key_rotate_view.c
  srcs/mlx_tools.c
  srcs/parse_get_texture.c
  srcs/parse_get_texture_img.c
  srcs/parse_init.c
  srcs/ray_init.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Todo: ⌨

#53 [refactoring] edit code readability
  Makefile
  cub3D
  include/cub3d.h
  include/ray_casting.h
  srcs/mlx_tools.c
  srcs/ray_dda.c
  srcs/ray_init.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Refactor: 🛠

#54 [done] mini_map
  Makefile
  cub3D
  include/cub3d.h
  srcs/main.c
  srcs/minimap_init.c
  srcs/mlx_key_event.c
  srcs/mlx_mouse_event.c
  srcs/mlx_tools.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Todo: ⌨

#55 [done] door 날먹
  cub3D
  include/cub3d.h
  map/infile4w.cub
  map/infile5.cub
  srcs/minimap_init.c
  srcs/mlx_key_event.c
  srcs/mlx_key_move.c
  srcs/mlx_key_rotate_view.c
  srcs/parse_get_map.c
  srcs/parse_get_map_error.c
  srcs/ray_dda.c
  srcs/ray_work.c
Labels: Priority: ⭑⭑⭑, Status: ✅, [Reason] Todo: ⌨
